"""Add unit_price to quotation_items

Revision ID: 099ceff98c05
Revises: 18813de6d256
Create Date: 2026-10-08 01:06:58.554750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099ceff98c05'
down_revision: Union[str, None] = '18813de6d256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation_items', sa.Column('unit_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation_items', 'unit_price')
    # ### end Alembic commands ###